-- 즐겨찾기 겹치는 것 없음. 일단 RANK로 진행
WITH RANK_RESTNAME AS(
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS FR
    FROM REST_INFO
)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM RANK_RESTNAME 
WHERE FR = 1
ORDER BY FOOD_TYPE DESC;