-- 코드를 입력하세요
-- 회원 ID를 기준으로 내림차순 DESC;
SELECT B.USER_ID, B.NICKNAME,
CONCAT(B.CITY,' ', B.STREET_ADDRESS1,' ', B.STREET_ADDRESS2) AS 전체주소,
CONCAT(
    SUBSTRING(B.TLNO,1,3),'-',
    SUBSTRING(B.TLNO,4,4),'-',
    SUBSTRING(B.TLNO,8,4)
) AS 전화번호
FROM USED_GOODS_BOARD A
    JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY USER_ID DESC;